#!/usr/bin/env bash

function BuildPackage {
  echo "Building package..."
  cd /workspaces/pypi_pymeteobridgesql
  python pymeteobridgesql/setup.py sdist
  echo "Package built!"
}

function UploadPackage {
  echo "Building package..."
  twine upload /workspaces/pypi_pymeteobridgesql/dist/*
  echo "Package built!"
}

